name: alfred-slack
version: 0.1.0.0
github: "satosystems/alfred-slack"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2023 Satoshi Ogata"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: Alfred integration for Slack
category: CLI

description: Please see the README on GitHub at <https://github.com/satosystems/alfred-slack#readme>

dependencies:
  - aeson
  - aeson-casing
  - async
  - base >= 4.7 && < 5
  - bytestring
  - case-insensitive
  - containers
  - directory
  - http-conduit
  - lens
  - mtl
  - string-conversions
  - text
  - time
  - unix

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  alfred-slack:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - alfred-slack
