name: alfred-slack
version: 0.1.0.0
github: "satosystems/alfred-slack"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2023 Satoshi Ogata"

extra-source-files:
  - README.md
  - CHANGELOG.md

synopsis: Alfred integration for Slack
category: CLI

description: Please see the README on GitHub at <https://github.com/satosystems/alfred-slack#readme>

flags:
  debug:
    description: Enable debug build (with -DDEBUG)
    manual: true
    default: true
  release:
    description: Enable release build (with -O2 and without -DDEBUG)
    manual: true
    default: false

dependencies:
  - MissingH
  - aeson
  - aeson-casing
  - async
  - base >= 4.7 && < 5
  - bytestring
  - case-insensitive
  - containers
  - directory
  - http-conduit
  - lens
  - mtl
  - network-uri
  - process
  - regex-tdfa
  - strict
  - string-conversions
  - text
  - time
  - unicode-transforms
  - unix
  - xml-conduit

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  when:
    - condition: flag(debug)
      cpp-options:
        - -DDEBUG
    - condition: flag(release)
      ghc-options:
        - -O2

executables:
  alfred-slack:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - alfred-slack
    when:
      - condition: flag(debug)
        cpp-options:
          - -DDEBUG
      - condition: flag(release)
        ghc-options:
          - -O2
